In [1]:
import pandas as pd

**Pandas mainly uses two objects.**
1.Series
2.Dataframe

In [3]:
data = pd.Series([1,2,3,4,5,6,7,8,9,10])
print(data)
data = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(data)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [5]:
data = {
    "Name":["Suman","Arif","Ahasan"],
    "Age":[22,24,23],
    "Faculty":["CSE","BBA","Agri"]
}
df = pd.DataFrame(data)
print(df)

     Name  Age Faculty
0   Suman   22     CSE
1    Arif   24     BBA
2  Ahasan   23    Agri

Loading Dataset (VERY IMPORTANT FOR ML)

In [12]:
df = pd.read_csv('Iris.csv')
df.head()
df.tail()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [16]:
print(df[["SepalLengthCm","SepalWidthCm"]])

     SepalLengthCm  SepalWidthCm
0              5.1           3.5
1              4.9           3.0
2              4.7           3.2
3              4.6           3.1
4              5.0           3.6
..             ...           ...
145            6.7           3.0
146            6.3           2.5
147            6.5           3.0
148            6.2           3.4
149            5.9           3.0

[150 rows x 2 columns]

In [19]:
df.iloc(0)
df[df["Id"]>30]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
30,31,4.8,3.1,1.6,0.2,Iris-setosa
31,32,5.4,3.4,1.5,0.4,Iris-setosa
32,33,5.2,4.1,1.5,0.1,Iris-setosa
33,34,5.5,4.2,1.4,0.2,Iris-setosa
34,35,4.9,3.1,1.5,0.1,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [25]:
data = {
    "Name":["Suman","Arif","Ahasan"],
    "Age":[22,24,23],
    "Faculty":["CSE","BBA","Agri"]
}
df = pd.DataFrame(data)
print(df)
df[df["Age"]>22]
df["Salary"] = df["Age"]*1000
df.head()

     Name  Age Faculty
0   Suman   22     CSE
1    Arif   24     BBA
2  Ahasan   23    Agri

     Name  Age Faculty  Salary
0   Suman   22     CSE   22000
1    Arif   24     BBA   24000
2  Ahasan   23    Agri   23000

**Data cleaning**

In [30]:
iris = pd.read_csv("Iris.csv")

iris.isnull()
iris.isnull().sum()
iris.dropna()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Age
0,1,5.1,3.5,1.4,0.2,Iris-setosa,5.843333
1,2,4.9,3.0,1.4,0.2,Iris-setosa,5.843333
2,3,4.7,3.2,1.3,0.2,Iris-setosa,5.843333
3,4,4.6,3.1,1.5,0.2,Iris-setosa,5.843333
4,5,5.0,3.6,1.4,0.2,Iris-setosa,5.843333

In [31]:
import pandas as pd

data = {
    "Department": ["IT", "HR", "IT", "HR", "Finance"],
    "Employee": ["John", "Sara", "Mike", "Anna", "Tom"],
    "Salary": [50000, 40000, 60000, 45000, 70000]
}

df = pd.DataFrame(data)
print(df)

  Department Employee  Salary
0         IT     John   50000
1         HR     Sara   40000
2         IT     Mike   60000
3         HR     Anna   45000
4    Finance      Tom   70000

In [35]:
df.groupby("Department")["Salary"].agg(["mean", "max", "min"])

               mean    max    min
Department
Finance     70000.0  70000  70000
HR          42500.0  45000  40000
IT          55000.0  60000  50000